# Generated by Django 5.2 on 2025-05-10 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_productos', '0002_presentacion_remove_producto_precio_precioproducto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='imagen',
            field=models.ImageField(null=True, upload_to='categorias/'),
        ),
    ]
